#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import time

os.system('cls')
print("****************************************************************")
print("*                                                              *")
print("*              Esta aplicación basada en mis                   *")
print("*           apuntes de clase como ejemplo de                   *")
print("*       digitalización de contenidos educativos,               *")
print("*              muestra de 'gamificación'                       *")
print("*           y estrategia de aprendizaje con TIC                *")
print("*                                                              *")
print("*                                                              *")
print("*             Matías Ignacio Campos - 2018                     *")
print("*       camposm@filo.uba.ar - campos.matias@gmail.com          *")
print("*                                                              *")
print("*           http://matias-campos.blogspot.com.ar               *")
print("*                                                              *")
print("****************************************************************")
print("                               |+|+|+|                         ")
print("")

time.sleep(4)
os.system('cls')

def menu():
    print(" -----------------------------------")
    print("         Menú Principal")
    print(" -----------------------------------")
    print(" \t1 - Introducción")
    print(" \t2 - Fonética")
    print(" \t3 - Morfología")
    print(" \t4 - Sintaxis")
    print(" \t5 - Historia y Cultura")
    print(" -----------------------------------")
    print(" \t0 - Salir")
    print(" -----------------------------------")
    
while True:
    menu()
    opcionMenu = input("\nElija una opción desde tu teclado >> ")
    if opcionMenu == "1":
        os.system('cls')
        print("--------------------------------\n")
        print("\tIntroducción al Griego Clásico")
        print("--------------------------------\n")
        print("\tLos académicos llaman 'Griego Clásico' a la lengua escrita reconstruida por Erasmo de Roterdam en sl S. XIII d.C.\n"
        "y que fue usada, para componer las obras escritas desde Pericles a Alejando Magno.\n"
        "Existen varios dialectos, como el eólico, el jónico. Se reconocen tradiciones propias de un tipo de disciplina.\n"
        "\nEs importante mantener presente que se trata de un tipo de lengua instrumental, a saber; "
              "a los meros fines de la escritura.\n"
        "Posteriormente Ventris, Blegen y otros realizaron aportes arqueológicos que permitieron reconstruir"
              "el griego arcaico que data de mucho tiempo atrás.")
        print("------------------------------>>>")
        input("pulsa 'Enter' para continuar")
        os.system('cls')
    elif opcionMenu == "2":
        os.system('cls')
        def fonetica():
            print("--------------------------------")
            print("    Lecciones de Fonética")
            print("--------------------------------")
            print("\t1 - Alfabeto")
            print("\t2 - Leyes")
            print("--------------------------------")
            print("\t0 - Volver")
            print("--------------------------------")
        while True:
            fonetica()
            opcionFon = input("\nElija una opción >>> ")
            if opcionFon == "1":
                os.system('cls')
                print("--------------------------------\n")
                print("Alfabeto")
                print("\n")
                print("El alfabeto fue introducido en el arcontado de Euclides (nada que ver con el matemático)")
                print("\n-------------------------------------------------------------------------------------------\n")
                print("\nLas letras de ALFABETO Griego cuenta con 24 elementos\n")
                print("   |      Letras Griegas   | Transcrip. |   Se pronuncia como:  |          Nombre        ")
                print("   | Mayúscula | Minúscula |  Latina    |                       | Castellano  -  Griego  ")
                print("1. |     Α     |     α     |     a      |  'a' breve o larga    |   'álfa'    -   ἄλφα   ")
                print("2. |     Β     |     β     |     b      |   'b' castellana      |   'béta'    -   βῆτα   ")
                print("3. |     Γ     |     γ     |     g      |'ga, gue, gui, go, gu  |   'gámma'   -   γάμμα  ")
                print("4. |     Δ     |     δ     |     d      |   'd' castellana      |   'délta'   -   δέλτα  ")
                print("5. |     Ε     |     ε     |     e      |     'e' breve         |   'epsilón' -   ἓ ψιλόν")
                print("6. |     Ζ     |     ζ     |     z      |        'ds'           |   'dseta'   -   ζῆτα   ")
                print("7. |     Η     |     η     |     e      |     'e' larga         |   'eta'     -   ἦτα    ")
                print("8. |     Θ     |     θ     |    th      |    za-ce-ci-zo-zu     |   'zeta'    -   ϑῆτα   ")
                print("9. |     Ι     |     ι     |     i      |         'i'           |   'iota'    -   ἰῶτα   ")
                print("10.|     Κ     |     κ     |     k      |      'k' - 'c'        |   'kappa'   -   κάππα  ")
                print("11.|     Λ     |     λ     |     l      |         'l'           |   'lambda'  -   λάμβδα ")
                print("12.|     Μ     |     μ     |     m      |          m            |   'my'      -   μῦ     ")
                print("13.|     Ν     |     ν     |     n      |          n            |   'ny'      -   νῦ     ")
                print("14.|     Ξ     |     ξ     |     x      |       x-cs-ks         |   'xi'      -   ξῖ      ")
                print("15.|     Ο     |     ο     |     o      |          o            |   'omicrón' -   ὂ μικρόν")
                print("16.|     Π     |     π     |     p      |          p            |   'pi'      -   πῖ      ")
                print("17.|     Ρ     |     ρ     |     r      |          r            |   'rho'     -   ῥῶ     ")
                print("18.|     Σ     |    σ-ς    |     s      |          s            |   'sigma'   -   σῖγμα   ")
                print("19.|     Τ     |     τ     |     t      |          t            |   'tau'     -   ταῦ     ")
                print("20.|     Υ     |     υ     |     ü      |    y - ü alemana      |   'ypsilón' -   ὖ ψιλόν ")
                print("21.|     Φ     |     φ     |     f      |          f            |   'fi'      -   φῖ       ")
                print("22.|     Χ     |     χ     |    x-ks    |          j            |   'ji'      -   χῖ       ")
                print("23.|     Ψ     |     ψ     |     ps     |         ps            |   'ps'      -   ψῖ       ")
                print("24 |     Ω     |     ω     |     o      |          o            |   'omega'   -   ὦ μέγα  ")
                print("------------------------------------------------------------------------------------------")
                input("pulsa una tecla para continuar")
                os.system('cls')
            elif opcionFon == "2":
                os.system('cls')
                print("-------------------------------")
                print("\t Leyes fonéticas")
                print("-------------------------------\n")
                print(" que rigen sobre las vocales")
                print(" Contracción")
                print("\n El encuentro de vocales ásperas, en medio de palabras, resulta en la mezcla de las vocales"
                "implicadas resultando una vocal largo o un diptongo...\n")
                print(" Crasis")
                print("Apofonía")
                print("Alargamiento")
                print("Elisión")
                print("Síncopa ")
                print("que rigen sobre las Consonates\n")
                print("Asimilación")
                print("Disimilación")
                print("Desaparición")
                print("Formación de consonantes dobles")
                print("Consonantes finales móviles")
                print("-------------------------------")
                input("pulsa una tecla para continuar")
                os.system('cls')
            elif opcionFon == "0":
                print("¿...volver al menú principal?")
                print("-------------------------------")
                input("pulsa 'Enter' para continuar")
                os.system('cls')
                break
    elif opcionMenu == "3":
        def morfologia():
            os.system('cls')
            print(" ---------------------------------------")
            print(" \tLecciones de Morfología")
            print(" ---------------------------------------")
            print(" \t1 - Declinación")
            print(" \t2 - Artículo")
            print(" \t3 - Sustantivo")
            print(" \t4 - Adjetivo")
            print(" \t5 - Comparativos y superlativos")
            print(" \t6 - Pronombres")
            print(" \t7 - Flexión Verbal")
            print(" ---------------------------------------")
            print(" \t0 - Volver al Menú Principal")
            print(" ---------------------------------------")
        while True:
            morfologia()
            opcionMorf = input("\nElija una opción: >>> ")
            if opcionMorf == "1":
                os.system('cls')
                print("-------------------------------\n")
                print("De la Declinación\n")
                print("Es la carácterìstica principal de las lenguas flexionadas que indica la funciòn "
                      "de géneo, número y la función sintáctica\n")
                print("-------------------------------")
                input("pulsa 'Enter' para continuar")
            elif opcionMorf == "2":
                os.system('cls')
                print("-------------------------------")
                print("Del Artículo\n")
                print("Femenino")
                print("||\n")
                print("Masculino")
                print("| ὁ | ὦ | τόν | τοῦ | τῷ || οἱ | οἱ | τούς | τῶν | τοῖς\n")
                print("Neutro")
                print("||")
                print("\n-------------------------------")
                input("pulsa 'Enter' para continuar  >>>")
            elif opcionMorf == "3":
                os.system('cls')
                print("-------------------------------")
                print("Del Sustantivo\n")
                print("El sustantivo es la clase de palabra que representa a los objetos y personas, "
                      "en tanto entidades, por ello les cabe el género y el número\n")
                print("Existen 3 tipos")
                print("1. Delinación")
                print("2. Declinación")
                print("3. Declinación")
                print("------------------------------->>>")
                input("pulsa 'Enter' para continuar")
            elif opcionMorf == "4":
                os.system('cls')
                print("-------------------------------")
                print("Del Adjetivo\n")
                print("El adjetivo es una clase de palabra con la que representa a las cualidades o atributos, "
                      "que poseen y caracterizan a los sustantivos\n")
                print("Existen 3 tipos")
                print("1. Clase | con 3 terminaciones.")
                print("2. Clase | con 2 terminaciones")
                print("3. Clase | con 2 terminaciones")
                print("------------------------------->>>")
                input("pulsa 'Enter' para continuar")
            elif opcionMorf == "5":
                os.system('cls')
                print("-------------------------------")
                print("Del Comparativo y el Superlativo\n")
                print("Representan los extremos de una relación entre dos elementos que definen su sentido "
                      "en relación recíproca.\n")
                print("------------------------------->>>")
                input("pulsa 'Enter' para continuar")
                os.system('cls')
            elif opcionMorf == "0":
                print("volver al Menú Principal")
                print("------------------------------->>>")
                input("pulsa 'Enter' para continuar")
                os.system('cls')
                break
            else:
                print("Presione una opción válida del Menú")
                print("-----------------------------------")
                input("pulsa 'Enter' para continua")
                os.system('cls')
    elif opcionMenu == "4":
        def sintaxis():
            os.system('cls')
            print("----------------------------------------")
            print("  De la Sintaxis                |")
            print("----------------------------------------")
            print(" \t1 - Bases del Análisis Sintáctico ")
            print(" \t2 - Los Casos                     ")
            print(" \t3 - Sustantivo                    ")
            print(" \t4 - Adjetivo                      ")
            print(" \t5 - Verbos                        ")
            print(" \t6 - Complementos                  ")
            print(" \t7 - Flexión Verbal                ")
            print("----------------------------------------")
            print(" \t0 - Volver al Menú Principal      ")
            print("----------------------------------------")
        while True:
            sintaxis()
            opcionSintax = input("\nElija una opción: >>> ")
            if opcionSintax == "1":
                os.system('cls')
                print("-------------------------------")
                print("Bases del Análisis Sintáctico\n")
                print("El análisis en el castellano...\n")
                print("---------------------------->>>")
                input("pulsa 'Enter' para volver")
                os.system('cls')
            elif opcionSintax == "2":
                os.system('cls')
                print("-------------------------------")
                print("De los Casos\n")
                print("| Nominativo:    | aplica para el sujeto y el predicativo del sujeto.             |")
                print("| Vocativo:      | aplica para la apelación.                                      |")
                print("| Acusativo:     | aplica para el objeto directo y sujeto de una oración relativa.|")
                print("| Genitivo:      | aplica para el especificativo.                                 |")
                print("| Dativo:        | aplica para los complementos y el objeto indirecto.            |")
                print("---------------------------->>>")
                input("pulsa 'Enter' para volver")
                os.system('cls')
            elif opcionSintax == "3":
                os.system('cls')
                print("-------------------------------")
                print("Sustantivos\n")
                print("Cumple la función de 'Núcleo del Sujeto'...\n")
                print("---------------------------->>>")
                input("pulsa 'Enter' para volver")
                os.system('cls')
            elif opcionSintax == "4":
                os.system('cls')
                print("-------------------------------")
                print("Adjetivos\n")
                print("Cumple la función de 'Modificador' de los sustantivos. Incluso, si posee artículo, se sustantiva.\n")
                print("---------------------------->>>")
                input("pulsa 'Enter' para volver")
                os.system('cls')
            elif opcionSintax == "5":
                os.system('cls')
                print("-------------------------------")
                print("Verbos\n")
                print("Los verbos son un tipo de palabra que representan la acción.\n")
                print("---------------------------->>>")
                input("pulsa 'Enter' para volver")
                os.system('cls')
            elif opcionSintax == "6":
                os.system('cls')
                print("-------------------------------")
                print("Complementos\n")
                print("Sirven para situar un contexto, un agente al núcleo.\n")
                print("---------------------------->>>")
                input("pulsa 'Enter' para volver")
                os.system('cls')
            elif opcionSintax == "7":
                os.system('cls')
                print("-------------------------------")
                print("Flexión Verbal\n")
                print("Paradigma de la conjugación verbal.\n")
                print("---------------------------->>>")
                input("pulsa 'Enter' para volver")
                os.system('cls')
            elif opcionSintax == "0":
                print("volver al Menú Principal")
                print("-------------------------->>>")
                input("pulsa 'Enter' para continuar")
                os.system('cls')
                break
            else:
                print("Presione una opción válida del Menú")
                print("----------------------------->>>")
                input("pulsa 'Enter' para continua")
                os.system('cls')
    elif opcionMenu == "0":
        print("¿desea salir de la aplicación?")
        print("----------------------------->>>")
        input("pulsa 'Enter' para continuar")
        quit()
    else:
        os.system('cls')
        print("Presione una opción válida del Menú en pantalla")
        print("-----------------------------------------------")
        input("pulsa 'Enter' para continuar")
        os.system('cls')